### ISSUE TITLE
From gallery : No such file or directory 

### ISSUE THREAD

**Issue by rsanjuan87** [WeTransfer/WeScan#347]
I post and refer here because it's maybe a bug in project
https://github.com/sawankumarbundelkhandi/edge_detection/issues/120

> Just ran your example and got this error and had pretty much the same on my project.
> 
```An Observatory debugger and profiler on iPhone 14 Pro Max is available at: http://127.0.0.1:52355/Am-AXM7VDfQ=/
The Flutter DevTools debugger and profiler on iPhone 14 Pro Max is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:52355/Am-AXM7VDfQ=/
flutter: /Users/quentinpayre/Library/Developer/CoreSimulator/Devices/B82FFF0C-19CC-4BA0-ABC2-9A29F6946FF7/data/Containers/Data/Application/62A6CEC7-5C81-4888-B8AE-E29E6588BC8E/Library/Application Support/1675089091.jpeg : _imagePath
flutter: success: true

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following PathNotFoundException was thrown resolving an image codec:
Cannot retrieve length of file, path =
'/Users/quentinpayre/Library/Developer/CoreSimulator/Devices/B82FFF0C-19CC-4BA0-ABC2-9A29F6946FF7/data/Containers/Data/Application/62A6CEC7-5C81-4888-B8AE-E29E6588BC8E/Library/Application
Support/1675089091.jpeg' (OS Error: No such file or directory, errno = 2)

When the exception was thrown, this was the stack:
#0      _checkForErrorResponse (dart:io/common.dart:42:9)
#1      _File.length.<anonymous closure> (dart:io/file_impl.dart:372:7)
<asynchronous suspension>
#2      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:998:31)
<asynchronous suspension>

Path:
/Users/quentinpayre/Library/Developer/CoreSimulator/Devices/B82FFF0C-19CC-4BA0-ABC2-9A29F6946FF7/data/Containers/Data/Application/62A6CEC7-5C81-4888-B8AE-E29E6588BC8E/Library/Application
Support/1675089091.jpeg```

**Comment by rsanjuan87** [comment]
Same here
https://github.com/sawankumarbundelkhandi/edge_detection/issues/109
